name: 02 - Two jobs

on:
    workflow_dispatch: 

jobs:
    job-one:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!"
    
    job-two:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world too!"
        