name: 03 - Sequence jobs

on:
    workflow_dispatch:
    # see the next workflow to understand this 
    workflow_call: 

jobs:
    job-one:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello first!"
    
    job-two:
        runs-on: ubuntu-latest
        needs: [job-one]           
        steps:
            - run: echo "hello second!"
        