name: 05 - Job Inputs

on:
  workflow_dispatch: 
    inputs:
      anything:
        type: string
        required: false
        default: 'is possible'

jobs:
  using-input-from-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'If you belive, anything $${{inputs.anything}}!'