name: 08 - Using secrets

on:
    workflow_dispatch: 

jobs:
    ill-tell-u-a-secret:
        runs-on: ubuntu-latest
        steps:
            - run: echo "my secret is ${{secrets.MY_SECRET}}"
              # gh secret set MY_SECRET
              # or create a .env file if using act
            - run: | 
                echo "secret doesn't echo, but go ahead and use them!"
                echo $(( 10 + ${{secrets.X}}))
