---
name: 10 - create job Outputs
on:
  workflow_dispatch:
    inputs:
      some_key:
        default: foo
        description: an input via workflow dispatch
        options: [foo, bar]
  workflow_call:
    inputs:
      some_key:
        default: bar
        description: an input via workflow call
        type: string
    outputs:
      out1:
        value: ${{ jobs.create-outputs.outputs.out1 }}
      out2:
        value: ${{ jobs.create-outputs.outputs.out2 }}
jobs:
  create-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the input
        run: echo "${{inputs.some_key}} via ${{github.event_name}}"
      - name: Create out1
        id: step1
        run: echo "OUT1=123" >> $GITHUB_OUTPUT
      - name: Create out2
        id: step2
        run: echo "OUT2=456" >> $GITHUB_OUTPUT
    outputs:
      out1: ${{steps.step1.outputs.OUT1}}
      out2: ${{steps.step2.outputs.OUT2}}
