name: 12 - create a commit
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  write-message:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Created at $(date +'%0Y.%0m.%0d') from commit ${GITHUB_SHA::7} via ${{github.event_name}}" > stamp.txt
          git status
          git config user.name "Leonardo Silveira"
          git config user.email "sombriks@gmail.com"
          git add .
          git commit -m "update stamp.txt"
          git push -u origin main
          echo "commits from actions does not trigger actions"

