name: 13 - Create a comment on a pull request
on:
  pull_request:
    branches:
      - main
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  comment-if-its-a-pr:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'github.ref_name ${{github.ref_name}}'
      - run: echo 'github.base_ref ${{github.base_ref}}'
      - run: echo 'github.event_name ${{github.event_name}}'
      - uses: actions/checkout@v4
      - run: gh pr list
      # - run: gh pr comment $${{github. }}
