name: 13 - Create a comment on a pull request
on:
  pull_request:
    branches:
      - main
jobs:
  comment-if-its-a-pr:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running from ${{github.ref_name}}'
      - run: gh pr list
