---
name: 14 - Use custom local action
on:
  workflow_dispatch: 
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: sombriks/gh-actions-playground/.github/actions/14-hello-reusable-action@main
        id: reusable
        with:
          name: 'AliceBob'
      - run: |
          echo "got from reusable: ${{steps.reusable.outputs.greet}}"
   